### ISSUE TITLE
Token images are not displayed in the main window

### ISSUE THREAD

**Issue by akolotov** [omni/omnibridge-nft-ui#26]
Images for some tokens are not displayed on the main window.

**xDai->ETH:**
![image](https://user-images.githubusercontent.com/20793260/123548375-38d7b580-d76d-11eb-8c94-546d528b9a31.png)

Account: [`0xBF3d6f830CE263CAE987193982192Cd990442B53`](https://blockscout.com/xdai/mainnet/address/0xBF3d6f830CE263CAE987193982192Cd990442B53)
Tokens: [[60, 61]](https://blockscout.com/xdai/mainnet/address/0x022E2426227E510123aABaFf4108Ddb6f59c2f8a), [[29]](https://blockscout.com/xdai/mainnet/address/0xf4993427b3B5C314005A152A6dD2978DA2468FfE)

**ETH->xDai:**
![image](https://user-images.githubusercontent.com/20793260/123548586-0aa6a580-d76e-11eb-81bc-2aceff124631.png)

Account: [`0xBF3d6f830CE263CAE987193982192Cd990442B53`](https://etherscan.io/address/0xBF3d6f830CE263CAE987193982192Cd990442B53)

Tokens: [[238453]](https://etherscan.io/address/0x60f80121c31a0d46b5279700f9df786054aa5ee5)

**Comment by akolotov** [comment]
The issue still exists:
![image](https://user-images.githubusercontent.com/20793260/123801136-a6f9b500-d8f2-11eb-9dde-ea735a64a088.png)
Does it make sense to provide any ability for user to re-fresh (reload) a thumbnail if it was not loaded by some reason?

**Comment by dan13ram** [comment]
@akolotov can you open the app in a new tab, does the issue still persist?

**Comment by akolotov** [comment]
I have asked one of my colleagues to check on his system and he also has tokens without images in NFT OB UI. We checked them manually on OpenSea and they indeed refer to pictures.

NFT OB UI:
![image](https://user-images.githubusercontent.com/20793260/123817530-ea5b2000-d900-11eb-83c2-34913bf220ac.png)

OpenSea:
![image](https://user-images.githubusercontent.com/20793260/123817782-1e364580-d901-11eb-8197-2cbda4adbbc8.png)

Here is the links to the tokens with missed images:
- https://opensea.io/assets/0x22cc8b3666e926bcbf58cb726143b2b044c80a0c/46974261294739181443868022823210332482961064921477538167143088111870011755556
- https://opensea.io/assets/0x7e789e2dd1340971de0a9bca35b14ac0939aa330/149702
- https://opensea.io/assets/0xe414a94e31f5f31e640a26d2822e8fef3328b667/10001

**Comment by dan13ram** [comment]
@akolotov I've updated the UI, can you please check if the tokens are showing up with the right images?

FYI:
https://opensea.io/assets/0x22cc8b3666e926bcbf58cb726143b2b044c80a0c/46974261294739181443868022823210332482961064921477538167143088111870011755556

This token doesn't have a valid URI as checked on etherscan, so it won't load on the UI.

Please check at https://xdai-omnibridge-nft-staging.web.app/

**Comment by akolotov** [comment]
It looks OK for me. I will close this issue and open another one if a new case appear.
