### ISSUE TITLE
Token 1085744 of RARI was not discovered

### ISSUE THREAD

**Issue by akolotov** [omni/omnibridge-nft-ui#27]
Although the token `1085744` of [RARI](https://blockscout.com/xdai/mainnet/address/0x7060E80328Bd1337228c68EFb3Bb8B8343a08de9) is owned by `0xBF3d6f830CE263CAE987193982192Cd990442B53` it is not displayed in the main window.

![image](https://user-images.githubusercontent.com/20793260/123548947-a4228700-d76f-11eb-91fe-1f5b3225ae5b.png)

**Comment by akolotov** [comment]
We found similar behavior with tokens owned by another account in the Ethereum Mainnet:

Here is the list of tokens in NFT OB UI:
![image](https://user-images.githubusercontent.com/20793260/123819864-c4cf1600-d902-11eb-8b9e-7d445cdc5ec8.png)

Here is the list of their tokens in OpenSea:
![image](https://user-images.githubusercontent.com/20793260/123819897-cf89ab00-d902-11eb-932f-f02357e9cec0.png)

The difference is in 4 tokens.

**Comment by dan13ram** [comment]
This should be fixed too 
Please check https://xdai-omnibridge-nft-staging.web.app/

**Comment by akolotov** [comment]
I see this token now. Thanks
