### ISSUE TITLE
Mark failed transfer on the history page

### ISSUE THREAD

**Issue by akolotov** [omni/omnibridge-nft-ui#29]
Currently the history page does not reflect failed transfers:

![image](https://user-images.githubusercontent.com/20793260/123549769-13e64100-d773-11eb-9f81-c82f395bc2ab.png)

The first (Jun, 2) transfer in the list was executed but filed: https://blockscout.com/xdai/mainnet/tx/0x5b08a6cd95ada0053d14a3a5e028d712cd8bf1610263cfc328cb8d04e6f934c4

The second (Jun, 10) transfer was executed successfully: https://blockscout.com/xdai/mainnet/tx/0x980e6309e586c463811dced3bfc0be3b475d695ecb998e887460f8bc92142ce8

Consider to mark the failed transfers like '_Failed_' instead of '_Claimed_'. Otherwise it could confuse like in the example above: the same token was transferred twice from the Ethereum Mainnet without a transfer from the xDai chain.

**Comment by dan13ram** [comment]
Hey @akolotov,
Curious to know what happens with `AffirmationCompleted` event is logged with `status = false`.
Is the token bridging reversed ? 
Are the tokens sent back to the user on mainnet in the above example of June 2nd?

**Comment by akolotov** [comment]
If a message transfer fails there is the ability to notify the mediator about this by calling the method `requestFailedMessageFix`. It will trigger a new AMB message to unlock tokens on the originating side. For example, in that case the transaction https://blockscout.com/xdai/mainnet/tx/0x40599abb9c4f3b5b119b5fdaad39db02fbbc118ff99f160a43294f4d7499570f initiated such kind of message. So, the token was unlocked: https://etherscan.io/tx/0x522b2f4d077ec6665c134aa9a77ae40c69ba11685131594a43e4adfee7609762. 

I could prepare a documentation page with the description how to unlock tokens as so we can refer to this page in the NFT OB UI as part of this issue resolving. What do you think?

**Comment by dan13ram** [comment]
Yes, that sounds great to me. We can add a link to this documentation for
the user to click whenever a transaction fails.

**Comment by dan13ram** [comment]
We could also provide the user the option on the UI to make that call since the data required for calling `requestFailedMessageFix` is available on the UI. Let me know what you think @akolotov

**Comment by dan13ram** [comment]
Closed in #37
