### ISSUE TITLE
Search tokens by the token name

### ISSUE THREAD

**Issue by akolotov** [omni/omnibridge-nft-ui#32]
The search functionality does not work for some tokens.

1. The EIP1155 tokens https://blockscout.com/xdai/mainnet/address/0x022E2426227E510123aABaFf4108Ddb6f59c2f8a are named as '_HashAvatars_'
2. The account `0xBF3d6f830CE263CAE987193982192Cd990442B53` owns the tokens `60` and `61`.
    ![image](https://user-images.githubusercontent.com/20793260/123558366-76a10200-d79e-11eb-98ac-9917da5e9b42.png)
3. If `hash`, `hashavatars`, `HA` or `HashAvatars` are entered in the search field, no tokens are available:
    ![image](https://user-images.githubusercontent.com/20793260/123558401-abad5480-d79e-11eb-8fa7-29c81453a0ad.png)

**Comment by dan13ram** [comment]
Currently we are not tracking names or symbols for erc1155 since they are not available in the official eip. But if you think its necessary then we can start doing so.

**Comment by akolotov** [comment]
We did a quick research and it looks like there are lots of EIP1155 token contracts extending the standard with the name and symbol (HashAvatars and UiniqueBubbles on the xDai, for example). So, I think it makes sense to support the look up operation by using the name/symbol for EIP1155 tokens as well.

**Comment by dan13ram** [comment]
That makes sense. Will get this working :)

**Comment by dan13ram** [comment]
@akolotov This should be fixed now too. Please check https://xdai-omnibridge-nft-staging.web.app/

**Comment by akolotov** [comment]
LGTM
