### ISSUE TITLE
Incorrect results for search by a token id

### ISSUE THREAD

**Issue by akolotov** [omni/omnibridge-nft-ui#33]
The account `0xBF3d6f830CE263CAE987193982192Cd990442B53` owns the following tokens:
- 6355 in [`0xCF964c89f509a8c0Ac36391c5460dF94B91daba5`](https://blockscout.com/xdai/mainnet/address/0xCF964c89f509a8c0Ac36391c5460dF94B91daba5)
- 60 and 61 in [`0x022E2426227E510123aABaFf4108Ddb6f59c2f8a`](https://blockscout.com/xdai/mainnet/address/0x022E2426227E510123aABaFf4108Ddb6f59c2f8a)
- 29 in [`0xf4993427b3B5C314005A152A6dD2978DA2468FfE`](https://blockscout.com/xdai/mainnet/address/0xf4993427b3B5C314005A152A6dD2978DA2468FfE)

If `60` is entered in the search field both 6355 and 60 are available for the selection:
![image](https://user-images.githubusercontent.com/20793260/123558819-f9c35780-d7a0-11eb-9b4c-a6a6ce087b29.png)

Although by entering one of 29, 61 and 6355 only one tokens remains on the screen:
![image](https://user-images.githubusercontent.com/20793260/123558944-dcdb5400-d7a1-11eb-841b-e922eb006458.png)

**Comment by dan13ram** [comment]
@akolotov This search works on name, symbol, address and tokenId for erc721 and address and tokenId for erc1155.
So when `60` was entered, the search returned results for tokenId 60 as well as address 0xCF964c89f509a8c0Ac36391c54_60_dF94B91daba5.

**Comment by akolotov** [comment]
Do you think it will not confuse a user? Especially if they have dozens of tokens on different addresses? Does it make sense to recognize the pattern to output more relevant look up results: 
- look for tokens by a contract's address if the search input starts with `0x`
- look for tokens by a contract's name/symbol and a token id otherwise

**Comment by dan13ram** [comment]
Sure that makes sense to me.
