### ISSUE TITLE
[Beta Feedback]: Bazinga

### ISSUE THREAD

**Issue by igorbarinov** [omni/omnibridge-nft-ui#48]
Satisfied: 
Very satisfied

Bugs/Issues:
If you have encountered any issues or bugs, please report here 

Additional comments:
If you have any additional comments or feedback that wasn't addressed above, please feel free to enter them in this section!

Attachment:
https://dl.airtable.com/.attachments/e14cc2cf6265834fc3339389e5e0684d/7f2a30aa/Screenshot2021-07-08at10.38.00.png

**Comment by ulyanas** [comment]
test issue
