### ISSUE TITLE
[Beta Feedback]: SNAFU: NFT was already claimed issue while claiming, tx failed

### ISSUE THREAD

**Issue by ulyanas** [omni/omnibridge-nft-ui#49]
name
SNAFU

Created
11/7/2021 19:41

Overall, how would you rate your experience with NFT Bridge?
Somewhat satisfied

If you encounter any issues or bugs, please report here
When I claimed the transaction it showed me an error: 'NFT was already claimed', but after I closed the popup the NFT was there, so I guess everything went right. But still, there is a failed transaction. I looked better and I actually found that in the same block another claim transaction was successful. Those are the 2 transactions:
SUCCESS: https://rinkeby.etherscan.io/tx/0x3542db7f6a9e6dc922022eb9551ff2c98ba9b6a792c950274dbb9c365e3e55f6
ERROR: https://rinkeby.etherscan.io/tx/0x5ee1f0d15091c6eccd59d48d1bd59a135c9ddaab365c9e285a7b4e3233157ea6

Didn't tried to bridge back yet.

Additional Comments
Very good looking and nice UX, congrats.

**Comment by akolotov** [comment]
The claim issue for the Rinkeby-xDai direction was addressed as part of the work under #53
