### ISSUE TITLE
[Beta Feedback]: Eporio: Request for xdai <-> polygon and also the sokol network

### ISSUE THREAD

**Issue by ulyanas** [omni/omnibridge-nft-ui#50]
name
Eporio

Created
11/7/2021 20:37

Overall, how would you rate your experience with NFT Bridge?
Neutral

If you encounter any issues or bugs, please report here

Additional Comments
Hi, I haven't tested the platform yet, but it looks neat.

My main question is, will it include NFT bridging for xdai <-> polygon and also the sokol network? If you can add these bridges I can do some testing as I am considering adding polygon to the Eporio platform and I will be able to share more constructive feedbacks.

If you have any updates on this topic feel free to email me at info@alexsyo.com

**Comment by akolotov** [comment]
The direction Kovan-Sokol has been added to the app
