### ISSUE TITLE
[Beta Feedback]: DAOSquare

### ISSUE THREAD

**Issue by igorbarinov** [omni/omnibridge-nft-ui#51]
Satisfied: 
Very satisfied

Bugs/Issues:
perfect now!

Additional comments:
i feel it's perfect now, plus, we can think about UI to view NFTs better!

Attachment:

**Comment by dan13ram** [comment]
Can you elaborate on what you mean by better UI for viewing NFTs ?

**Comment by akolotov** [comment]
Closed until new details appear
