### ISSUE TITLE
Allows to disable the claim functionality per direction and per token basis

### ISSUE THREAD

**Issue by akolotov** [omni/omnibridge-nft-ui#53]
The issue is to port [the functionality of the fungible tokens OB](https://github.com/omni/omnibridge-ui/issues/262).

In some specific scenarios the bridge oracles can be configured to automatically execute transfers for some specific direction (e.g. Rinkeby-xDai) or for some specific token so there is no need for users to use the claim functionality in this case. Moreover the request to claim tokens confuses users since they could receive the error for the claim operation since it already performed by the oracles.

Consider to provide a configuration parameter available on the app deployment phase as so the claim window will not appear for some specific direction or for the tokens specified in the parameter.

In general the claim functionality could be switched off in several ways:
- per direction basis, e.g. the claim is required for ETH-xDai but it is not necessary for Rinkeby-xDai
- per token basis, e.g. the claim is not disabled for entire direction but it is switched off for transfers of some specific token

**Comment by dan13ram** [comment]
Closed by #57
