### ISSUE TITLE
[Beta Feedback]: OpenSea Rinkeby

### ISSUE THREAD

**Issue by igorbarinov** [omni/omnibridge-nft-ui#55]
Satisfied: 
Somewhat dissatisfied

Bugs/Issues:
One more thing.

I tried minting a new NFT on OpenSea (Rinkeby) 
It's minted, but doesn't show up on Etherscan Rinkeby bc it's an ERC1155.  i can see the txn.
I am expecting to see this 1155 in the Bridge UI, which i think supports 1155s, but do not see it.  

Thanks!

Additional comments:

Attachment:

**Comment by dan13ram** [comment]
@akolotov can we get more details on this NFT ? address and tokenId ?

**Comment by akolotov** [comment]
> @akolotov can we get more details on this NFT ? address and tokenId ?

So far I received this transaction from the issue originator: https://rinkeby.etherscan.io/tx/0x03fc2915afd54a34daeaeaf5b8102f0a7c9dd33919844e98c283ab5c5ad9fd76. Seems this transaction mints the EIP1155 token mentioned in the issue.

**Comment by dan13ram** [comment]
This token is
```
address: 0x88b48f654c30e99bc2e4a1559b4dcf1ad93fa656
tokenId: 0x881a01bba8182e14624c046fd5880c84d14a150700000000000001000000000
owner: 0x881a01bba8182e14624c046fd5880c84d14a1507
```
I've verified that it does show up under 1155 tokens. I think this is a false positive. 
Please reopen if necessary
