### ISSUE TITLE
[Beta Feedback]: Peerion

### ISSUE THREAD

**Issue by igorbarinov** [omni/omnibridge-nft-ui#56]
Satisfied: 
Somewhat satisfied

Bugs/Issues:
When claiming the token on Rinkeby side, we encountered a contract error. The UI then told us that the token was already claimed. We checked the contract and there it says execution reverted, but after checking if the token made it to our address on Rinkeby, it was there.

Here is the tx: https://rinkeby.etherscan.io/tx/0x7fe931e2bff96f1b2eb8bbc1494e48c845f86e4e52da3a7a63d9a5efb55b120c

Additional comments:
Overall, the UI/UX is very clean and easy to navigate.

Attachment:
https://dl.airtable.com/.attachments/c24a3fce2f92352b31b3bf4cee47dd6f/9fc7f5e6/xDaiNFTBridge.PNG

**Comment by akolotov** [comment]
Thanks for report! The issue with the claim was already mentioned in #49. We created the issue #53 to make possible flexible configuration for the claim functionality.

**Comment by akolotov** [comment]
The claim issue for the Rinkeby-xDai direction was addressed as part of the work under #53
