### ISSUE TITLE
[Beta Feedback]: 1Hive Solar

### ISSUE THREAD

**Issue by igorbarinov** [omni/omnibridge-nft-ui#58]
Satisfied: 
Very satisfied

Bugs/Issues:
Everything has been good , no bugs ... 
1. I have transferred from xdai to Rinkeby with success
2. I then transfered back from Rinkeby to xDai to another wallet address and that worked fine aswell.

Additional comments:
The idea for this bridge is great, I like how clean it is and how i found all of my nfts. Thanks xDai team !

Attachment:

**Comment by akolotov** [comment]
No new issues/suggestion reported
