### ISSUE TITLE
Adjustments for a mobile device

### ISSUE THREAD

**Issue by akolotov** [omni/omnibridge-nft-ui#61]
Consider to go through general scenarios on the browser embedded in the wallets (e.g. Mobile MetaMask) and make corresponding adjustments of the elements.

E.g. the Transfer button on the screenshot below is hardly recognizable 

![telegram-cloud-photo-size-2-5456315389458888444-y](https://user-images.githubusercontent.com/20793260/126375729-9482f9c9-f41a-4ab9-a96d-500501ec4e90.jpg)

**Comment by dan13ram** [comment]
Closed in #63
