### ISSUE TITLE
Use OpenSea API to get images for ENS NFTs

### ISSUE THREAD

**Issue by akolotov** [omni/omnibridge-nft-ui#62]
The [ENS NFT contract](https://etherscan.io/address/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85) does not follow the standard and don't provide the tokenURI method so the tokens have no metadata associated with them. That is why the tokens images cannot be displayed for ENS NFTs in the OmniBridge UI.

Consider to hardcode a special handling for the ENS NFTs in the Ethereum Mainnet and their bridged equivalent as so images from OpenSea (https://opensea.io/assets/ens) loaded into the OmniBridge UI.

**Comment by akolotov** [comment]
It makes sense to make the functionality to have a special handling to upload images more common as so in the future we can add exceptions for other tokens (recall the issue with the token representing a ticket to DevCon?)

**Comment by dan13ram** [comment]
Closing this issue. #79 adds the necessary changes.
