### ISSUE TITLE
[Beta Feedback]: SNAFU

### ISSUE THREAD

**Issue by igorbarinov** [omni/omnibridge-nft-ui#65]
Satisfied: 
Somewhat satisfied

Bugs/Issues:
Hi, I bridged an erc1155 nft from xdai to rinkeby and it worked successfully.
I went to https://rinkeby.rarible.com/ and I can see my NFT there, nut when I try to put it on sell rarible fails with this error: `this.contract.methods.approve is not a function` and this message on console: `Create fixed price error TypeError: this.contract.methods.approve is not a function`. I don't know if it's a Rarible bug on rinkeby or maybe that function of the contract wasn't included on the mainnet. Could you please give it a check?

This is the contract on xDai: https://blockscout.com/xdai/mainnet/tokens/0xED1eFC6EFCEAAB9F6d609feC89c9E675Bf1efB0a/token-transfers

This is the token I bridged: https://testnets.opensea.io/assets/0x7f52120d9dc822f4b28726c8b4e57f33bcbc71db/17

I also tried this with an ERC721 with a different contract and it worked fine on rarible.

Additional comments:

Attachment:

**Comment by akolotov** [comment]
`1155` token contracts do not contain the `approve` method as per [the EIP1155 standard](https://eips.ethereum.org/EIPS/eip-1155). So, it is definitely the issue on the Rarible side.

**Comment by akolotov** [comment]
Closed until new details appear
