### ISSUE TITLE
Add a warning for Crypto Stamp tokens

### ISSUE THREAD

**Issue by akolotov** [omni/omnibridge-nft-ui#74]
Consider to display a warning like `Bridging Crypto stamp token via NFT OmniBridge is not recommended. Please use a dedicated Crypto Stamp the bridge on https://crypto.post.at.` if a crypto stamp token is chosen. The idea is that bridging of these tokens will break the logic the Crypto Stamp project is building around separate tokens and collections. 

This is a list of contracts NFT OB UI must track to display the warning:

Ethereum Mainnet:
- 0x7e789E2dd1340971De0A9bca35b14AC0939Aa330 - Crypto stamp 1 (ERC-721 NFT)
- 0x818737EeC8A5350756DA40D5DDAfda8A84Ade107 - Crypto stamp 2 Presale (ERC-1155 token)
- 0xa7f87E8D193E29bf1eD050Fdd511B79Fe0264d8B - Crypto stamp 2 (ERC-721 NFT)
- 0x478059f577Cb739f0AF0f37A365DD069Ba5BD8Be - Crypto stamp Golden Unicorn (ERC-721 NFT)
- 0xe38251813B08C2c048B0582A52501acA5Df0BaAb - Crypto stamp 3 (ERC-721 NFT)
- 0x574317b5167521d2E3E34469a6993102FBbd92ed - Crypto stamp Collections (ERC-721 NFT + factory that deploys Collection contracts)

xDai: 
- 0x41CDc950315D5afb5722dfFe0A32153e4DE85456 - Crypto stamp 3 Presale (ERC-1155 token)
- 0x5550f0D022f706d03AD25A72C477684d3416193F - Crypto stamp 3 (ERC-721 NFT)
- 0xFfe8c00c14dEAb02F4734fe3106452B611089323 - Crypto stamp Collections (ERC-721 NFT + factory that deploys Collection contracts)
- 0xee60885fD9365042E923ED2960BA4cEc474E4446 - Bridged Crypto stamp 1 (ERC-721 NFT, minimal proxy)
- 0xC5EF97923D98d509DeC20fE96Fb6C1d3c221e927 - Bridged Crypto stamp 2 Presale (ERC-1155 token, minimal proxy)
- 0x143e0E54695E7EB13571B019F87e927c1098066C - Bridged Crypto stamp 2 (ERC-721 NFT, minimal proxy)
- 0x77E25Fde78CC1052072B2E4f491764c568e60c32 - Bridged Crypto stamp Golden Unicorn (ERC-721 NFT, minimal proxy)

**Comment by dan13ram** [comment]
Closing this. #79 incorporates the necessary changes
