### ISSUE TITLE
[Beta Feedback]: chenrui5199@gmail.com

### ISSUE THREAD

**Issue by igorbarinov** [omni/omnibridge-nft-ui#78]
Satisfied: 
Somewhat satisfied

Bugs/Issues:
Does the UI have a limit on the number of displays? I found that not all the NFTs in my wallet are displayed . e.g .I have over 350 poaps , but it only shows me 100 of them .

Additional comments:

Attachment:

**Comment by akolotov** [comment]
@dan13ram is it possible that the OB UI hits a limit to request metadata by the token URI?

**Comment by dan13ram** [comment]
By default the graph returns only 100 results I think. I'm updating to the highest allowed which is 1000.

**Comment by dan13ram** [comment]
Closing this. #79 incorporates the necessary changes
